In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df=pd.read_csv("Book3.csv")
df

area  bedrooms  age    price
0  2600       3.0    20  550000
1  3000       4.0    15  565000
2  3200       NaN    18  610000
3  3600       3.0    30  595000
4  4000       5.0     8  760000

In [3]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [4]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age    price
0  2600       3.0    20  550000
1  3000       4.0    15  565000
2  3200       3.0    18  610000
3  3600       3.0    30  595000
4  4000       5.0     8  760000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [6]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [7]:
reg.intercept_

383724.9999999998

In [8]:
reg.predict([[3000,3,40]])

D:\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [9]:
reg.predict([[2500,4,5]])

D:\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [13]:
d=pd.read_csv("score.csv")
d

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
..    ...     ...
91    5.8      60
92    4.4      44
93    6.1      63
94    3.7      37
95    8.0      84

[96 rows x 2 columns]

In [22]:
import math
mean_Scores=math.floor(df[Scores].mean())
mean_Scores

NameError: name 'Scores' is not defined